### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by kwonzero** [kwonzero/gh-flow-practice#1]
## tasks

- [x] Print fizz, if i is multiple of 3.
- [ ] Print buzz, if i is multiple of 5.
- [ ] Print fizzbuzz, if i is multiple of 15.
- [x] Otherwise, print i itself.

## References

- [Fizzbuzz wikipedia](https://www.wikipedia.org/)
